(()=>{
'use strict';
const $=s=>document.querySelector(s);
const ARCHIVE_KEY='goshaBatchArchiveV1';
const MIGRATION_KEY='goshaBatchMigration20260823';
const DB_NAME='GoshaBatchArchive';
const STORE='records';
const RECORD='archive';
const CACHE_NAME='gosha-batch-archive-v1';
const CACHE_URL=new URL('./__gosha_batch_archive__',location.href).href;
const NEW_BATCH='LEMON OG 500/3100\nSmoked: 0\n\n\nBLUE DREAM 200/1400\nSmoked: 0';
let records=[];

function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function validList(v){return Array.isArray(v)?v.filter(x=>x&&typeof x.text==='string'&&x.text.trim()):[]}
function dedupe(list){const seen=new Set(),out=[];for(const x of list.sort((a,b)=>(+b.savedAt||0)-(+a.savedAt||0))){const k=x.id||hash(x.text);if(seen.has(k))continue;seen.add(k);out.push({...x,id:k})}return out}
function deriveLabel(text){const names=[...String(text).matchAll(/^(.+?)\s+\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?\s*$/gm)].map(m=>m[1].trim()).filter(Boolean);return names.length?names.slice(0,3).join(' + '):'Notebook record'}
function makeRecord(text,label){return {id:hash(text),label:label||deriveLabel(text),savedAt:Date.now(),text:String(text)}}
function localRead(){try{return validList(JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]'))}catch(_){return []}}
function localWrite(list){try{localStorage.setItem(ARCHIVE_KEY,JSON.stringify(list));return true}catch(_){return false}}
function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}
async function idbRead(){try{const db=await openDb();return await new Promise(resolve=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(RECORD);r.onsuccess=()=>resolve(validList(r.result));r.onerror=()=>resolve([]);tx.oncomplete=()=>db.close()})}catch(_){return []}}
async function idbWrite(list){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(list,RECORD);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return true}catch(_){return false}}
async function cacheRead(){try{if(!('caches'in window))return [];const c=await caches.open(CACHE_NAME),r=await c.match(CACHE_URL);return r?validList(JSON.parse(await r.text())):[]}catch(_){return []}}
async function cacheWrite(list){try{if(!('caches'in window))return false;const c=await caches.open(CACHE_NAME);await c.put(CACHE_URL,new Response(JSON.stringify(list),{headers:{'content-type':'application/json'}}));return true}catch(_){return false}}
async function loadRecords(){const [a,b,c]=await Promise.all([Promise.resolve(localRead()),idbRead(),cacheRead()]);records=dedupe([...a,...b,...c]);return records}
async function saveRecords(){records=dedupe(records);const [idb,cache]=await Promise.all([idbWrite(records),cacheWrite(records)]);const local=localWrite(records);return {local,idb,cache}}
async function snapshot(text,label){text=String(text||'');if(!text.trim())return null;const id=hash(text),found=records.find(r=>r.id===id);if(found){found.savedAt=Date.now();if(label)found.label=label}else records.unshift(makeRecord(text,label));await saveRecords();renderRecords();return records.find(r=>r.id===id)||null}
function setNotebook(text){const n=$('#note');if(!n)return;n.value=text;n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}))}
async function activateRecord(rec){const n=$('#note');if(!n||!rec)return;const current=n.value;if(current.trim()&&hash(current)!==rec.id)await snapshot(current,deriveLabel(current)+' · active before switch');setNotebook(rec.text);closeRecords();document.querySelector('.navBtn[data-target="notebook"]')?.click();toast('Record loaded into main notebook')}
function installStyles(){if($('#goshaArchiveStyle'))return;const s=document.createElement('style');s.id='goshaArchiveStyle';s.textContent=`
.recordsTrigger{margin-top:10px!important;padding:7px 9px!important;opacity:.52!important;font:650 .62rem/1 ui-monospace,SFMono-Regular,Menlo,monospace!important;letter-spacing:.13em!important;text-transform:uppercase!important}.recordsTrigger:hover,.recordsTrigger:focus{opacity:.85!important}
#goshaRecordsOverlay{position:fixed;z-index:120000;inset:0;display:none;background:rgba(0,0,0,.94);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);padding:max(18px,env(safe-area-inset-top)) 12px max(18px,env(safe-area-inset-bottom));overflow:auto}#goshaRecordsOverlay.show{display:block}
.recordsShell{width:min(760px,100%);margin:0 auto;border:1px solid rgba(134,255,40,.16);border-radius:20px;background:linear-gradient(180deg,rgba(5,10,6,.99),#000);overflow:hidden;box-shadow:0 24px 70px rgba(0,0,0,.7)}.recordsHead{display:flex;align-items:center;gap:10px;padding:14px 15px;border-bottom:1px solid rgba(134,255,40,.1);font:700 .66rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.16em;color:#cce9c5}.recordsHead b{margin-right:auto}.recordsHead button{border:1px solid rgba(134,255,40,.14);border-radius:9px;background:transparent;color:#8fa38a;padding:7px 9px}.recordsBody{padding:10px}.recordCard{border:1px solid rgba(134,255,40,.1);border-radius:14px;padding:12px;margin-bottom:8px;background:rgba(255,255,255,.012)}.recordMeta{display:flex;justify-content:space-between;gap:10px;margin-bottom:8px}.recordMeta b{color:#dcebd8;font:700 .73rem/1.25 ui-monospace,SFMono-Regular,Menlo,monospace}.recordMeta span{color:#60705d;font:600 .58rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap}.recordPreview{margin:0 0 10px;max-height:88px;overflow:hidden;white-space:pre-wrap;color:#7f8d7b;font:500 .68rem/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}.recordActions{display:flex;gap:7px}.recordActions button{border:1px solid rgba(134,255,40,.18);border-radius:10px;background:rgba(134,255,40,.03);color:#cce9c5;padding:8px 10px;font:650 .62rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em}.recordActions .primary{border-color:rgba(134,255,40,.3);color:#e6ffe0}.recordsEmpty{padding:24px;color:#667363;text-align:center;font:600 .68rem/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}
`;
document.head.appendChild(s)}
function installUI(){installStyles();const vault=$('#goshaVaultCard');if(vault&&!$('#goshaRecordsBtn')){const b=document.createElement('button');b.id='goshaRecordsBtn';b.type='button';b.className='btn recordsTrigger';b.textContent='Records';b.onclick=openRecords;vault.appendChild(b)}if(!$('#goshaRecordsOverlay')){const o=document.createElement('section');o.id='goshaRecordsOverlay';o.setAttribute('aria-label','Archived notebook records');o.innerHTML='<div class="recordsShell"><div class="recordsHead"><span>◉</span><b>RECORDS // ARCHIVE</b><button id="goshaArchiveCurrent" type="button">ARCHIVE CURRENT</button><button id="goshaRecordsClose" type="button">CLOSE</button></div><div class="recordsBody" id="goshaRecordsBody"></div></div>';document.body.appendChild(o);$('#goshaRecordsClose').onclick=closeRecords;$('#goshaArchiveCurrent').onclick=async()=>{const n=$('#note');if(!n)return;await snapshot(n.value,deriveLabel(n.value));toast('Current notebook archived')};o.addEventListener('click',e=>{if(e.target===o)closeRecords()})}renderRecords()}
function openRecords(){renderRecords();$('#goshaRecordsOverlay')?.classList.add('show')}
function closeRecords(){$('#goshaRecordsOverlay')?.classList.remove('show')}
function renderRecords(){const body=$('#goshaRecordsBody');if(!body)return;if(!records.length){body.innerHTML='<div class="recordsEmpty">NO ARCHIVED BATCHES</div>';return}body.innerHTML=records.map(r=>`<article class="recordCard" data-id="${esc(r.id)}"><div class="recordMeta"><b>${esc(r.label||deriveLabel(r.text))}</b><span>${new Date(+r.savedAt||Date.now()).toLocaleDateString('en-GB')}</span></div><pre class="recordPreview">${esc(r.text.split(/\r?\n/).slice(0,8).join('\n'))}</pre><div class="recordActions"><button class="primary" data-open="${esc(r.id)}" type="button">OPEN IN MAIN</button></div></article>`).join('');body.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>activateRecord(records.find(r=>r.id===b.dataset.open)))}
async function migrateNewBatch(){let done=false;try{done=localStorage.getItem(MIGRATION_KEY)==='1'}catch(_){}if(done)return;const n=$('#note');if(!n)return;const current=n.value;if(current.trim()&&current.trim()!==NEW_BATCH.trim()){const saved=await snapshot(current,'Previous batch · '+deriveLabel(current));if(!saved){toast('Archive failed — new batch not activated');return}}setNotebook(NEW_BATCH);await snapshot(NEW_BATCH,'Current batch · LEMON OG + BLUE DREAM');try{localStorage.setItem(MIGRATION_KEY,'1')}catch(_){}toast('Previous batch archived · new batch ready')}
async function boot(){await loadRecords();installUI();let tries=0;const waitVault=()=>{const count=$('#vaultCount');if(count&&count.textContent&&!count.textContent.startsWith('—')){migrateNewBatch();return}if(tries++<60)setTimeout(waitVault,100);else migrateNewBatch()};waitVault()}
function start(){let tries=0;const go=()=>{if($('#note')&&$('#settingsView'))boot();else if(tries++<40)setTimeout(go,100)};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
