(()=>{
'use strict';
const $=s=>document.querySelector(s);
const ARCHIVE_KEY='goshaBatchArchiveV2',LEGACY_ARCHIVE_KEY='goshaBatchArchiveV1';
const MIGRATION_KEY='goshaBatchMigration20260823';
const DB_NAME='GoshaBatchArchive',STORE='records',RECORD='archive';
const CACHE_NAME='gosha-batch-archive-v2',CACHE_URL=new URL('./__gosha_batch_archive_v2__',location.href).href;
const NEW_BATCH='LEMON OG 500/3100\nSmoked: 0\n\n\nBLUE DREAM 200/1400\nSmoked: 0';
let records=[];
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
function hash(text){let h=2166136261;for(let i=0;i<String(text).length;i++){h^=String(text).charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
function semanticText(text){return String(text||'').split(/\r?\n/).map(x=>x.trim().replace(/\s+/g,' ')).filter(x=>x&&!/^(?:total(?:\s+earned)?|total\s+sold|left)\s*:/i.test(x)).join('\n')}
function semanticHash(text){return hash(semanticText(text))}
function headers(text){return [...String(text||'').matchAll(/^(.+?)\s+(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)\s*$/gm)].map(m=>({name:m[1].trim(),acquired:+m[2],spent:+m[3]})).filter(x=>x.name)}
function signature(text){const h=headers(text);return h.length?h.map(x=>x.name.toLowerCase().replace(/\s+/g,' ')+'@'+x.acquired+'/'+x.spent).join('|'):'text@'+semanticHash(text)}
function batchId(text){return 'b-'+hash(signature(text))}
function deriveLabel(text){const names=headers(text).map(x=>x.name);return names.length?names.slice(0,4).join(' + '):'Notebook record'}
function abbrev(name){const n=String(name||'').trim().toUpperCase();const known={'BLUE DREAM':'BD','PINEAPPLE OG':'PA OG','LEMON OG':'L OG'};if(known[n])return known[n];const w=n.split(/\s+/).filter(Boolean);const suffix=w[w.length-1]==='OG'?' OG':'';const body=suffix?w.slice(0,-1):w;return (body.map(x=>x[0]).join('')||n.slice(0,3))+suffix}
function shortLabel(text){const n=headers(text).map(x=>abbrev(x.name));return n.length?n.join(' & '):'RECORD'}
function version(text,savedAt){return {hash:hash(text),semanticHash:semanticHash(text),text:String(text),savedAt:+savedAt||Date.now()}}
function collapseVersions(list){const map=new Map();for(const raw of Array.isArray(list)?list:[]){if(!raw||typeof raw.text!=='string'||!raw.text.trim())continue;const v=version(raw.text,raw.savedAt);const old=map.get(v.semanticHash);if(!old){map.set(v.semanticHash,v);continue}const richer=v.text.length>old.text.length?v:old;richer.savedAt=Math.min(+old.savedAt||Date.now(),+v.savedAt||Date.now());map.set(v.semanticHash,richer)}return [...map.values()].sort((a,b)=>a.savedAt-b.savedAt)}
function normalizeOne(x){if(!x||typeof x.text!=='string'||!x.text.trim())return null;const started=+(x.startedAt||x.savedAt||x.updatedAt)||Date.now(),updated=+(x.updatedAt||x.savedAt||x.startedAt)||started;let versions=collapseVersions(Array.isArray(x.versions)?x.versions:[]);if(!versions.some(v=>v.semanticHash===semanticHash(x.text)))versions=collapseVersions([...versions,version(x.text,updated)]);const latest=versions.reduce((a,b)=>(b.savedAt>=a.savedAt?b:a),versions[0])||version(x.text,updated);return {id:batchId(x.text),label:x.label||deriveLabel(x.text),startedAt:started,updatedAt:Math.max(updated,latest.savedAt),text:latest.text,versions}}
function merge(list){const map=new Map();for(const raw of Array.isArray(list)?list:[]){const r=normalizeOne(raw);if(!r)continue;const old=map.get(r.id);if(!old){map.set(r.id,r);continue}old.startedAt=Math.min(old.startedAt,r.startedAt);old.updatedAt=Math.max(old.updatedAt,r.updatedAt);old.versions=collapseVersions([...old.versions,...r.versions]);const latest=old.versions.reduce((a,b)=>(b.savedAt>=a.savedAt?b:a),old.versions[0]);if(latest){old.text=latest.text;old.updatedAt=Math.max(old.updatedAt,latest.savedAt)}if(!old.label&&r.label)old.label=r.label}return [...map.values()].sort((a,b)=>b.startedAt-a.startedAt)}
function parseList(raw){try{return Array.isArray(raw)?raw:JSON.parse(raw||'[]')}catch(_){return []}}
function localRead(){try{return [...parseList(localStorage.getItem(ARCHIVE_KEY)),...parseList(localStorage.getItem(LEGACY_ARCHIVE_KEY))]}catch(_){return []}}
function localWrite(list){try{localStorage.setItem(ARCHIVE_KEY,JSON.stringify(list));return true}catch(_){return false}}
function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}
async function idbRead(){try{const db=await openDb();return await new Promise(resolve=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(RECORD);r.onsuccess=()=>resolve(Array.isArray(r.result)?r.result:[]);r.onerror=()=>resolve([]);tx.oncomplete=()=>db.close()})}catch(_){return []}}
async function idbWrite(list){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(list,RECORD);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return true}catch(_){return false}}
async function cacheRead(){try{if(!('caches'in window))return [];const c=await caches.open(CACHE_NAME),r=await c.match(CACHE_URL);return r?parseList(await r.text()):[]}catch(_){return []}}
async function cacheWrite(list){try{if(!('caches'in window))return false;const c=await caches.open(CACHE_NAME);await c.put(CACHE_URL,new Response(JSON.stringify(list),{headers:{'content-type':'application/json'}}));return true}catch(_){return false}}
function nativeRead(){try{if(window.AndroidVault&&typeof AndroidVault.loadArchive==='function')return parseList(AndroidVault.loadArchive())}catch(_){}return []}
function nativeWrite(list){try{if(window.AndroidVault&&typeof AndroidVault.saveArchive==='function'){AndroidVault.saveArchive(JSON.stringify(list));return true}}catch(_){}return false}
async function loadRecords(){const [a,b,c]=await Promise.all([Promise.resolve(localRead()),idbRead(),cacheRead()]);records=merge([...a,...b,...c,...nativeRead()]);return records}
async function saveRecords(){records=merge(records);const [idb,cache]=await Promise.all([idbWrite(records),cacheWrite(records)]);const local=localWrite(records),native=nativeWrite(records);window.dispatchEvent(new CustomEvent('goshaArchiveChanged',{detail:{records:records.slice(),health:{local,idb,cache,native}}}));return {local,idb,cache,native}}
async function snapshot(text,label,startedAt){text=String(text||'');if(!text.trim())return null;const id=batchId(text),now=Date.now(),sh=semanticHash(text);let r=records.find(x=>x.id===id);if(!r){r={id,label:label||deriveLabel(text),startedAt:+startedAt||now,updatedAt:now,text,versions:[version(text,now)]};records.unshift(r)}else{r.startedAt=Math.min(r.startedAt,+startedAt||r.startedAt);if(label&&!/active before switch/i.test(label))r.label=label;const existing=r.versions.find(v=>(v.semanticHash||semanticHash(v.text))===sh);if(!existing){r.versions.push(version(text,now));r.updatedAt=now;r.text=text}else if(text.length>existing.text.length){existing.text=text;existing.hash=hash(text);r.text=text}r.versions=collapseVersions(r.versions)}await saveRecords();renderRecords();return records.find(x=>x.id===id)||r}
function setNotebook(text){const n=$('#note');if(!n)return;n.value=text;n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}))}
async function activateRecord(rec){const n=$('#note');if(!n||!rec)return;const current=n.value;if(current.trim()&&(batchId(current)!==rec.id||semanticHash(current)!==semanticHash(rec.text)))await snapshot(current,deriveLabel(current));setNotebook(rec.text);closeRecords();document.querySelector('.navBtn[data-target="notebook"]')?.click();toast('Record loaded into main notebook')}
function installStyles(){if($('#goshaArchiveStyle'))return;const s=document.createElement('style');s.id='goshaArchiveStyle';s.textContent=`.recordsTrigger{margin-top:10px!important;padding:7px 9px!important;opacity:.5!important;font:650 .62rem/1 ui-monospace,SFMono-Regular,Menlo,monospace!important;letter-spacing:.13em!important;text-transform:uppercase!important}.recordsTrigger:hover,.recordsTrigger:focus{opacity:.85!important}#goshaRecordsOverlay{position:fixed;z-index:120000;inset:0;display:none;background:rgba(0,0,0,.95);backdrop-filter:blur(16px);padding:max(18px,env(safe-area-inset-top)) 12px max(18px,env(safe-area-inset-bottom));overflow:auto}#goshaRecordsOverlay.show{display:block}.recordsShell{width:min(760px,100%);margin:0 auto;border:1px solid rgba(134,255,40,.16);border-radius:20px;background:linear-gradient(180deg,rgba(5,10,6,.99),#000);overflow:hidden}.recordsHead{display:flex;align-items:center;gap:9px;padding:14px 15px;border-bottom:1px solid rgba(134,255,40,.1);font:700 .66rem/1 ui-monospace,monospace;letter-spacing:.14em;color:#cce9c5}.recordsHead b{margin-right:auto}.recordsHead button,.recordActions button{border:1px solid rgba(134,255,40,.16);border-radius:9px;background:transparent;color:#9bad97;padding:8px 9px}.recordsBody{padding:10px}.recordCard{border:1px solid rgba(134,255,40,.1);border-radius:14px;padding:12px;margin-bottom:8px;background:rgba(255,255,255,.012)}.recordMeta{display:flex;justify-content:space-between;gap:10px;margin-bottom:8px}.recordMeta b{color:#dcebd8;font:700 .73rem/1.25 ui-monospace,monospace}.recordMeta span{color:#60705d;font:600 .58rem/1 ui-monospace,monospace;white-space:nowrap}.recordPreview{margin:0 0 10px;max-height:88px;overflow:hidden;white-space:pre-wrap;color:#7f8d7b;font:500 .68rem/1.45 ui-monospace,monospace}.recordSub{color:#53604f;font:600 .58rem/1.3 ui-monospace,monospace;margin:-2px 0 9px}.recordActions{display:flex;gap:7px}.recordActions .primary{border-color:rgba(134,255,40,.3);color:#e6ffe0}.recordsEmpty{padding:24px;color:#667363;text-align:center;font:600 .68rem/1.5 ui-monospace,monospace}`;document.head.appendChild(s)}
function installUI(){installStyles();const vault=$('#goshaVaultCard');if(vault&&!$('#goshaRecordsBtn')){const b=document.createElement('button');b.id='goshaRecordsBtn';b.type='button';b.className='btn recordsTrigger';b.textContent='Records';b.onclick=openRecords;vault.appendChild(b)}if(!$('#goshaRecordsOverlay')){const o=document.createElement('section');o.id='goshaRecordsOverlay';o.innerHTML='<div class="recordsShell"><div class="recordsHead"><span>◉</span><b>RECORDS // ARCHIVE</b><button id="goshaArchiveCurrent" type="button">ARCHIVE CURRENT</button><button id="goshaRecordsClose" type="button">CLOSE</button></div><div class="recordsBody" id="goshaRecordsBody"></div></div>';document.body.appendChild(o);$('#goshaRecordsClose').onclick=closeRecords;$('#goshaArchiveCurrent').onclick=async()=>{const n=$('#note');if(n){await snapshot(n.value,deriveLabel(n.value));toast('Current batch archived')}};o.addEventListener('click',e=>{if(e.target===o)closeRecords()})}renderRecords()}
function openRecords(){renderRecords();$('#goshaRecordsOverlay')?.classList.add('show')}
function closeRecords(){$('#goshaRecordsOverlay')?.classList.remove('show')}
function renderRecords(){const body=$('#goshaRecordsBody');if(!body)return;if(!records.length){body.innerHTML='<div class="recordsEmpty">NO ARCHIVED BATCHES</div>';return}body.innerHTML=records.map(r=>`<article class="recordCard"><div class="recordMeta"><b>${esc(shortLabel(r.text))}</b><span>${new Date(r.startedAt).toLocaleDateString('en-GB')}</span></div><div class="recordSub">${r.versions.length} protected version${r.versions.length===1?'':'s'} · updated ${new Date(r.updatedAt).toLocaleDateString('en-GB')}</div><pre class="recordPreview">${esc(r.text.split(/\r?\n/).slice(0,8).join('\n'))}</pre><div class="recordActions"><button class="primary" data-open="${esc(r.id)}" type="button">OPEN IN MAIN</button></div></article>`).join('');body.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>activateRecord(records.find(r=>r.id===b.dataset.open)))}
async function migrateNewBatch(){let done=false;try{done=localStorage.getItem(MIGRATION_KEY)==='1'}catch(_){}if(done)return;const n=$('#note');if(!n)return;const current=n.value;if(current.trim()&&current.trim()!==NEW_BATCH.trim()){const saved=await snapshot(current,'Previous batch · '+deriveLabel(current));if(!saved){toast('Archive failed — new batch not activated');return}}const health=await saveRecords();if(Object.values(health).filter(Boolean).length<2){toast('Archive safety check failed — keeping current batch');return}setNotebook(NEW_BATCH);await snapshot(NEW_BATCH,'Current batch · LEMON OG + BLUE DREAM');try{localStorage.setItem(MIGRATION_KEY,'1')}catch(_){}toast('Previous batch secured · new batch ready')}
window.GoshaArchive={getRecords:()=>records.map(r=>({...r,versions:r.versions.slice()})),refresh:loadRecords,snapshot,batchId,shortLabel,abbrev,semanticHash};
async function boot(){await loadRecords();await saveRecords();installUI();let tries=0;const waitVault=()=>{const count=$('#vaultCount');if(count&&count.textContent&&!count.textContent.startsWith('—')){migrateNewBatch();return}if(tries++<60)setTimeout(waitVault,100);else migrateNewBatch()};waitVault()}
function start(){let tries=0;const go=()=>{if($('#note')&&$('#settingsView'))boot();else if(tries++<40)setTimeout(go,100)};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();