(()=>{
'use strict';
const $=s=>document.querySelector(s),SELECT_KEY='goshaBatchStatsSelectedV1';
const fmt=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(Math.round((Number(n)+Number.EPSILON)*100)/100),money=n=>'€'+fmt(n);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let selected=new Set(),pickerOpen=false,queued=false;
function loadSelected(){try{selected=new Set(JSON.parse(localStorage.getItem(SELECT_KEY)||'[]'))}catch(_){selected=new Set()}}
function saveSelected(){try{localStorage.setItem(SELECT_KEY,JSON.stringify([...selected]))}catch(_){}}
function parse(text){const lines=String(text||'').split(/\r?\n/),rows=[];let p=null;const pair=/(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)/g;for(const line of lines){const t=line.trim();if(!t)continue;const h=t.match(/^(.+?)\s+(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)\s*$/);if(h&&/[A-Za-zÀ-ž]/.test(h[1])){p={name:h[1].trim(),acquired:+h[2],spent:+h[3],sold:0,earned:0,smoked:0,tx:0};rows.push(p);continue}if(!p)continue;const sm=t.match(/^(?:smoked|used)\s*:?\s*(\d+(?:\.\d+)?)/i);if(sm){p.smoked=+sm[1];continue}if(/^\s*(?:Total(?:\s+earned)?|Total\s+sold|Left)\s*:/i.test(t))continue;for(const m of line.matchAll(pair)){p.sold+=+m[1];p.earned+=+m[2];p.tx++}}for(const x of rows){x.unitCost=x.acquired?x.spent/x.acquired:0;x.left=Math.max(0,x.acquired-x.sold-x.smoked);x.avg=x.sold?x.earned/x.sold:0;x.net=x.earned-x.sold*x.unitCost;x.leftToEarn=x.left*x.avg}return rows}
function combine(texts){const by=new Map();let earned=0,sold=0,net=0,tx=0,left=0,leftToEarn=0;for(const text of texts){for(const p of parse(text)){earned+=p.earned;sold+=p.sold;net+=p.net;tx+=p.tx;left+=p.left;leftToEarn+=p.leftToEarn;const key=p.name.trim().toUpperCase();let r=by.get(key);if(!r){r={name:p.name,sold:0,earned:0,net:0,tx:0,left:0,leftToEarn:0};by.set(key,r)}r.sold+=p.sold;r.earned+=p.earned;r.net+=p.net;r.tx+=p.tx;r.left+=p.left;r.leftToEarn+=p.leftToEarn}}return {rows:[...by.values()].sort((a,b)=>b.earned-a.earned),earned,sold,net,tx,left,leftToEarn,avg:sold?earned/sold:0}}
function dateShort(ts){const d=new Date(+ts||Date.now());return String(d.getMonth()+1).padStart(2,'0')+'/'+String(d.getDate()).padStart(2,'0')}
function installStyle(){if($('#batchPickerStyle'))return;const s=document.createElement('style');s.id='batchPickerStyle';s.textContent=`
#batchPicker{display:none;margin-top:8px;border:1px solid rgba(134,255,40,.14);border-radius:12px;background:rgba(0,0,0,.96);overflow:hidden;box-shadow:inset 0 1px 0 rgba(255,255,255,.015)}#batchPicker.show{display:block}.batchPickerHead{display:flex;justify-content:space-between;gap:10px;padding:9px 10px;border-bottom:1px solid rgba(134,255,40,.08);color:#647360;font:650 8px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.13em}.batchPickerList{padding:6px}.batchPick{width:100%;display:grid;grid-template-columns:22px 1fr auto;align-items:center;gap:8px;margin:4px 0;padding:9px 10px;border:1px solid rgba(134,255,40,.09);border-radius:9px;background:rgba(255,255,255,.008);color:#8e9c8a;text-align:left;font:650 9px/1.15 ui-monospace,SFMono-Regular,Menlo,monospace}.batchPick i{width:12px;height:12px;border:1px solid rgba(134,255,40,.25);border-radius:3px;display:block;position:relative}.batchPick.selected{border-color:rgba(134,255,40,.27);color:#d9ecd4;background:rgba(134,255,40,.035)}.batchPick.selected i:after{content:'✓';position:absolute;left:1px;top:-2px;color:#86ff28;font-size:11px}.batchPick .batchDate{color:#60705d;font-size:8px}.batchPick.live{opacity:.78}.batchPick.live i{border-radius:50%;background:#86ff28;box-shadow:0 0 8px rgba(134,255,40,.5)}.batchPick.live i:after{display:none}.batchMultiTag{margin-left:7px;color:#86ff28;font-size:7px;vertical-align:top}`;document.head.appendChild(s)}
function archive(){return window.GoshaArchive&&typeof GoshaArchive.getRecords==='function'?GoshaArchive.getRecords():[]}
function currentId(){const n=$('#note');return n&&window.GoshaArchive?GoshaArchive.batchId(n.value):'live'}
function currentShort(){const n=$('#note');return n&&window.GoshaArchive?GoshaArchive.shortLabel(n.value):'LIVE'}
function installPicker(){const controls=$('#goshaDashboard .dashControls'),batch=$('#goshaDashboard .dashScope[data-mode="batch"]');if(!controls||!batch)return false;installStyle();if(!$('#batchPicker')){const p=document.createElement('div');p.id='batchPicker';p.innerHTML='<div class="batchPickerHead"><span>BATCH MATRIX // INCLUDE</span><span id="batchPickCount">1 ACTIVE</span></div><div class="batchPickerList" id="batchPickerList"></div>';controls.appendChild(p)}if(!batch.dataset.multiBound){batch.dataset.multiBound='1';batch.addEventListener('click',()=>{pickerOpen=!pickerOpen;$('#batchPicker')?.classList.toggle('show',pickerOpen);setTimeout(()=>{renderPicker();apply()},0)})}const dash=$('#goshaDashboard');if(!dash.dataset.multiOtherBound){dash.dataset.multiOtherBound='1';dash.addEventListener('click',e=>{const b=e.target.closest('.dashScope,.dashDaySelect,.dashArrow');if(b&&b.dataset.mode!=='batch'&&!b.matches('[data-mode="batch"]')){pickerOpen=false;$('#batchPicker')?.classList.remove('show')}})}renderPicker();return true}
function renderPicker(){const out=$('#batchPickerList');if(!out)return;const cid=currentId(),recs=archive().filter(r=>r.id!==cid);const validIds=new Set(recs.map(r=>r.id));for(const id of [...selected])if(!validIds.has(id))selected.delete(id);saveSelected();let html=`<button class="batchPick selected live" type="button" disabled><i></i><b>${esc(currentShort())}</b><span class="batchDate">LIVE</span></button>`;for(const r of recs){const on=selected.has(r.id);html+=`<button class="batchPick${on?' selected':''}" data-batch-id="${esc(r.id)}" type="button"><i></i><b>${esc((window.GoshaArchive&&GoshaArchive.shortLabel(r.text))||r.label||'BATCH')}</b><span class="batchDate">${dateShort(r.startedAt)}</span></button>`}out.innerHTML=html;out.querySelectorAll('[data-batch-id]').forEach(b=>b.onclick=()=>{const id=b.dataset.batchId;if(selected.has(id))selected.delete(id);else selected.add(id);saveSelected();renderPicker();apply()});const count=$('#batchPickCount');if(count)count.textContent=(1+selected.size)+' INCLUDED';const batch=$('#goshaDashboard .dashScope[data-mode="batch"]');if(batch){let tag=batch.querySelector('.batchMultiTag');if(selected.size){if(!tag){tag=document.createElement('sup');tag.className='batchMultiTag';batch.appendChild(tag)}tag.textContent='+'+selected.size}else tag?.remove()}}
function isBatchActive(){return $('#goshaDashboard .dashScope[data-mode="batch"]')?.classList.contains('active')}
function apply(){if(!isBatchActive())return;const n=$('#note');if(!n)return;const cid=currentId(),recs=archive(),texts=[n.value];for(const id of selected){const r=recs.find(x=>x.id===id);if(r&&r.id!==cid)texts.push(r.text)}const d=combine(texts),out=$('#dashProducts');if(!out)return;$('#dashEarned').textContent=money(d.earned);$('#dashSold').textContent=fmt(d.sold);$('#dashProfit').textContent=money(d.net);$('#dashTransactions').textContent=fmt(d.tx);$('#dashAverage').textContent=money(d.avg);$('#dashLeft').textContent=fmt(d.left);$('#dashTx').textContent=d.tx+' TX';const le=$('#dashLeftToEarn');if(le)le.textContent=money(d.leftToEarn);$('#dashScopeLabel').textContent=texts.length===1?'WHOLE BATCH':texts.length+' BATCHES COMBINED';$('#dashDelta').textContent=texts.length===1?'LIVE TOTAL':'LIVE + '+(texts.length-1)+' ARCHIVE'+(texts.length===2?'':'S');$('#dashDelta').classList.remove('down');out.innerHTML=d.rows.length?d.rows.map(p=>{const share=d.earned?Math.max(0,Math.min(100,p.earned/d.earned*100)):0;return `<article class="dashProduct"><div class="dashProductHead"><b>${esc(p.name)}</b><span class="dashBadge">${p.tx} TX</span></div><div class="dashRow"><span>EARNED</span><strong>${money(p.earned)}</strong></div><div class="dashRow"><span>SOLD</span><strong>${fmt(p.sold)}</strong></div><div class="dashRow"><span>NET</span><strong>${money(p.net)}</strong></div><div class="dashRow"><span>AVG / UNIT</span><strong>${money(p.sold?p.earned/p.sold:0)}</strong></div><div class="dashRow"><span>REMAINING</span><strong>${fmt(p.left)}</strong></div><div class="dashRow leftEarnRow"><span>LEFT TO EARN</span><strong>${money(p.leftToEarn)}</strong></div><div class="dashMeter"><i style="width:${share}%"></i></div></article>`}).join(''):'<div class="dashEmpty">NO SIGNAL // Selected batches contain no transactions yet.</div>';setTimeout(()=>{const all=$('#allLeftToEarn');if(all)all.textContent=money(d.leftToEarn)},0)}
function schedule(){if(queued)return;queued=true;setTimeout(()=>{queued=false;renderPicker();apply()},0)}
function boot(){loadSelected();let tries=0;const go=()=>{if(!installPicker()){if(tries++<60)setTimeout(go,100);return}$('#note')?.addEventListener('input',schedule,{passive:true});$('#note')?.addEventListener('change',schedule);window.addEventListener('goshaArchiveChanged',schedule);$('#goshaDashboard')?.addEventListener('click',schedule);schedule()};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();