(()=>{
'use strict';
const $=s=>document.querySelector(s),SELECT_KEY='goshaBatchStatsSelectedV1',DAY=86400000;
const fmt=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(Math.round((Number(n)+Number.EPSILON)*100)/100),money=n=>'€'+fmt(n);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let selected=new Set(),pickerOpen=false,queued=false;
function loadSelected(){try{selected=new Set(JSON.parse(localStorage.getItem(SELECT_KEY)||'[]'))}catch(_){selected=new Set()}}
function saveSelected(){try{localStorage.setItem(SELECT_KEY,JSON.stringify([...selected]))}catch(_){}}
function pairs(text){return [...String(text||'').matchAll(/(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)/g)].map(m=>({qty:+m[1],price:+m[2]}))}
function parse(text,useCorrection=false){const lines=String(text||'').split(/\r?\n/),rows=[];let p=null;for(const line of lines){const t=line.trim();if(!t)continue;const h=t.match(/^(.+?)\s+(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)\s*$/);if(h&&/[A-Za-zÀ-ž]/.test(h[1])){p={name:h[1].trim(),acquired:+h[2],spent:+h[3],smoked:0,days:[]};rows.push(p);continue}if(!p)continue;const sm=t.match(/^(?:smoked|used)\s*:?\s*(\d+(?:\.\d+)?)/i);if(sm){p.smoked=+sm[1];continue}if(/^\s*(?:Total(?:\s+earned)?|Total\s+sold|Left)\s*:/i.test(t))continue;if(pairs(line).length){const seg=line.split('|');for(let i=0;i<seg.length&&i<50;i++){const tx=pairs(seg[i]);if(!p.days[i])p.days[i]={sold:0,earned:0,tx:0};p.days[i].sold+=tx.reduce((a,x)=>a+x.qty,0);p.days[i].earned+=tx.reduce((a,x)=>a+x.price,0);p.days[i].tx+=tx.length}}}for(const x of rows){x.unitCost=x.acquired?x.spent/x.acquired:0;x.sold=x.days.reduce((a,d)=>a+(d?.sold||0),0);x.earned=x.days.reduce((a,d)=>a+(d?.earned||0),0);x.tx=x.days.reduce((a,d)=>a+(d?.tx||0),0);const calc=Math.max(0,x.acquired-x.sold-x.smoked);x.left=useCorrection?(window.GoshaInventoryCorrection?.get?.(x.name,calc)??calc):calc;x.avg=x.sold?x.earned/x.sold:0;x.net=x.earned-x.sold*x.unitCost;x.leftToEarn=x.left*x.avg}return rows}
function batchDays(products){return Math.max(0,...products.map(p=>p.days.length))}
function archive(){return window.GoshaArchive&&typeof GoshaArchive.getRecords==='function'?GoshaArchive.getRecords():[]}
function currentId(){const n=$('#note');return n&&window.GoshaArchive?GoshaArchive.batchId(n.value):'live'}
function currentShort(){const n=$('#note');return n&&window.GoshaArchive?GoshaArchive.shortLabel(n.value):'LIVE'}
function dayStamp(ts){const d=new Date(+ts||Date.now());return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()}
function dateShort(ts){const d=new Date(+ts||Date.now());return String(d.getMonth()+1).padStart(2,'0')+'/'+String(d.getDate()).padStart(2,'0')}
function allBatchObjects(){const n=$('#note');if(!n)return[];const cid=currentId(),recs=archive(),currentRec=recs.find(r=>r.id===cid);const out=[{id:cid,text:n.value,startedAt:currentRec?.startedAt||Date.now(),live:true,label:currentShort()}];for(const r of recs){if(r.id===cid)continue;out.push({id:r.id,text:r.text,startedAt:r.startedAt||r.updatedAt||0,live:false,label:(window.GoshaArchive&&GoshaArchive.shortLabel(r.text))||r.label||'BATCH'})}return out}
function chosenBatches(){const all=allBatchObjects(),cid=currentId();return all.filter(b=>b.id===cid||selected.has(b.id))}
function planBatches(batches){const plan=batches.map(b=>{const products=parse(b.text,b.live);return {...b,products,count:batchDays(products),start:dayStamp(b.startedAt)}}).sort((a,b)=>a.start-b.start);for(let i=plan.length-2;i>=0;i--){const cur=plan[i],next=plan[i+1];if(!cur.count)continue;const expectedEnd=cur.start+(cur.count-1)*DAY;if(cur.start>=next.start||expectedEnd>next.start)cur.start=next.start-(cur.count-1)*DAY}return plan}
function inferredStartMap(){return new Map(planBatches(allBatchObjects()).map(b=>[b.id,b.start]))}
function collectTimeline(batches){const plan=planBatches(batches),map=new Map();for(const b of plan){for(let i=0;i<b.count;i++){const stamp=b.start+i*DAY;let day=map.get(stamp);if(!day){day={stamp,rows:[],batchIds:new Set()};map.set(stamp,day)}day.batchIds.add(b.id);for(const p of b.products){const d=p.days[i];if(!d)continue;day.rows.push({batchId:b.id,name:p.name,unitCost:p.unitCost,sold:d.sold||0,earned:d.earned||0,tx:d.tx||0})}}}if(!map.size)return{plan,days:[]};const keys=[...map.keys()].sort((a,b)=>a-b),days=[];for(let s=keys[0];s<=keys[keys.length-1];s+=DAY)days.push(map.get(s)||{stamp:s,rows:[],batchIds:new Set()});return{plan,days}}
function aggregateBatches(batches,mode){const{plan,days}=collectTimeline(batches),windows={week1:7,week2:14,week3:21,month:30};const size=windows[mode]||days.length,selectedDays=mode==='batch'?days:days.slice(0,Math.min(size,days.length));const by=new Map(),perBatchProduct=new Map();let earned=0,sold=0,net=0,tx=0;for(const day of selectedDays){for(const p of day.rows){const key=p.name.trim().toUpperCase(),bp=p.batchId+'|'+key;let r=by.get(key);if(!r){r={name:p.name,sold:0,earned:0,net:0,tx:0,left:0,leftToEarn:0};by.set(key,r)}let q=perBatchProduct.get(bp);if(!q){q={sold:0,earned:0};perBatchProduct.set(bp,q)}const rowNet=p.earned-p.sold*p.unitCost;r.sold+=p.sold;r.earned+=p.earned;r.net+=rowNet;r.tx+=p.tx;q.sold+=p.sold;q.earned+=p.earned;earned+=p.earned;sold+=p.sold;net+=rowNet;tx+=p.tx}}let left=0,leftToEarn=0;const endStamp=selectedDays.length?selectedDays[selectedDays.length-1].stamp:-Infinity;for(const b of plan){if(b.start>endStamp)continue;for(const p of b.products){const key=p.name.trim().toUpperCase(),bp=b.id+'|'+key,q=perBatchProduct.get(bp)||{sold:0,earned:0};const calculated=Math.max(0,p.acquired-q.sold-p.smoked);const remaining=(mode==='batch'&&b.live)?(window.GoshaInventoryCorrection?.get?.(p.name,calculated)??calculated):calculated;const avg=q.sold?q.earned/q.sold:0,potential=remaining*avg;left+=remaining;leftToEarn+=potential;let r=by.get(key);if(!r){r={name:p.name,sold:0,earned:0,net:0,tx:0,left:0,leftToEarn:0};by.set(key,r)}r.left+=remaining;r.leftToEarn+=potential}}return{rows:[...by.values()].sort((a,b)=>b.earned-a.earned),earned,sold,net,tx,left,leftToEarn,avg:sold?earned/sold:0,days:selectedDays.length,totalDays:days.length,start:selectedDays[0]?.stamp||0,end:selectedDays[selectedDays.length-1]?.stamp||0}}
function installStyle(){if($('#batchPickerStyle'))return;const s=document.createElement('style');s.id='batchPickerStyle';s.textContent=`.batchScopeWrap{display:grid;grid-template-columns:minmax(0,1fr) 31px;gap:4px;min-width:0}.batchScopeWrap .dashScope{width:100%;height:100%}.batchSelectorToggle{border:1px solid rgba(134,255,40,.16);border-radius:10px;background:rgba(134,255,40,.018);color:rgba(160,255,125,.65);font:800 13px/1 ui-monospace,SFMono-Regular,Menlo,monospace;min-width:0;padding:0}.batchMultiTag{margin-left:5px;color:#86ff28;font-size:7px;vertical-align:top}#batchPicker{display:grid;grid-template-rows:0fr;opacity:0;margin-top:0;border:1px solid transparent;border-radius:13px;background:linear-gradient(180deg,rgba(4,9,4,.99),rgba(0,0,0,.99));overflow:hidden}#batchPicker.show{grid-template-rows:1fr;opacity:1;margin-top:8px;border-color:rgba(134,255,40,.17)}#batchPicker>div{min-height:0}.batchPickerHead{display:flex;justify-content:space-between;gap:10px;padding:10px 11px;border-bottom:1px solid rgba(134,255,40,.08);color:#647360;font:650 8px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.13em}.batchPickerList{padding:7px}.batchPick{width:100%;display:grid;grid-template-columns:22px 1fr auto;align-items:center;gap:8px;margin:4px 0;padding:10px;border:1px solid rgba(134,255,40,.09);border-radius:10px;background:rgba(255,255,255,.008);color:#8e9c8a;text-align:left;font:650 9px/1.15 ui-monospace,SFMono-Regular,Menlo,monospace}.batchPick i{width:12px;height:12px;border:1px solid rgba(134,255,40,.25);border-radius:3px;display:block;position:relative}.batchPick.selected{border-color:rgba(134,255,40,.29);color:#d9ecd4;background:rgba(134,255,40,.04)}.batchPick.selected i:after{content:'✓';position:absolute;left:1px;top:-2px;color:#86ff28;font-size:11px}.batchPick .batchDate{color:#60705d;font-size:8px}.batchPick.live i{border-radius:50%;background:#86ff28}.batchTimelineHint{padding:8px 11px 10px;color:#53604f;font:600 8px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace;border-top:1px solid rgba(134,255,40,.06)}@media(max-width:620px){.batchScopeWrap{grid-column:auto}}`;document.head.appendChild(s)}
function installPicker(){const controls=$('#goshaDashboard .dashControls'),batch=$('#goshaDashboard .dashScope[data-mode="batch"]');if(!controls||!batch)return false;installStyle();if(!$('#batchScopeWrap')){const wrap=document.createElement('div');wrap.id='batchScopeWrap';wrap.className='batchScopeWrap';batch.parentNode.insertBefore(wrap,batch);wrap.appendChild(batch);const toggle=document.createElement('button');toggle.id='batchSelectorToggle';toggle.className='batchSelectorToggle';toggle.type='button';toggle.textContent='▼';wrap.appendChild(toggle);toggle.onclick=e=>{e.stopPropagation();pickerOpen=!pickerOpen;toggle.textContent=pickerOpen?'▲':'▼';$('#batchPicker')?.classList.toggle('show',pickerOpen);renderPicker()}}if(!$('#batchPicker')){const p=document.createElement('div');p.id='batchPicker';p.innerHTML='<div><div class="batchPickerHead"><span>BATCHES // INCLUDE IN STATS</span><span id="batchPickCount">LATEST ONLY</span></div><div class="batchPickerList" id="batchPickerList"></div><div class="batchTimelineHint">Selected batches form one calendar timeline.</div></div>';controls.appendChild(p)}renderPicker();return true}
function renderPicker(){const out=$('#batchPickerList');if(!out)return;const cid=currentId(),recs=archive().filter(r=>r.id!==cid),validIds=new Set(recs.map(r=>r.id));for(const id of [...selected])if(!validIds.has(id))selected.delete(id);saveSelected();const starts=inferredStartMap();let html=`<button class="batchPick selected live" type="button" disabled><i></i><b>${esc(currentShort())}</b><span class="batchDate">LATEST</span></button>`;for(const r of recs.sort((a,b)=>(starts.get(a.id)||0)-(starts.get(b.id)||0))){const on=selected.has(r.id),label=(window.GoshaArchive&&GoshaArchive.shortLabel(r.text))||r.label||'BATCH';html+=`<button class="batchPick${on?' selected':''}" data-batch-id="${esc(r.id)}" type="button"><i></i><b>${esc(label)}</b><span class="batchDate">${dateShort(starts.get(r.id)||r.startedAt)}</span></button>`}out.innerHTML=html;out.querySelectorAll('[data-batch-id]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.batchId;if(selected.has(id))selected.delete(id);else selected.add(id);saveSelected();renderPicker();schedule()});const count=$('#batchPickCount');if(count)count.textContent=selected.size?`${1+selected.size} INCLUDED`:'LATEST ONLY'}
function activeMode(){return $('#goshaDashboard .dashScope.active')?.dataset.mode||($('#dashDaySelect')?.classList.contains('active')?'day':'batch')}
function supportedMode(mode){return['batch','week1','week2','week3','month'].includes(mode)}
function apply(){const mode=activeMode();if(!supportedMode(mode)||selected.size===0)return;const batches=chosenBatches(),d=aggregateBatches(batches,mode),out=$('#dashProducts');if(!out)return;$('#dashEarned').textContent=money(d.earned);$('#dashSold').textContent=fmt(d.sold);$('#dashProfit').textContent=money(d.net);$('#dashTransactions').textContent=fmt(d.tx);$('#dashAverage').textContent=money(d.avg);$('#dashLeft').textContent=fmt(d.left);$('#dashTx').textContent=d.tx+' TX';const le=$('#dashLeftToEarn');if(le)le.textContent=money(d.leftToEarn);const labels={week1:'WEEK 1',week2:'WEEKS 1–2',week3:'WEEKS 1–3',month:'FIRST 30 DAYS',batch:'WHOLE SELECTED RUN'};$('#dashScopeLabel').textContent=(labels[mode]||'WHOLE SELECTED RUN')+' // '+batches.length+' BATCHES';const meta=$('#dashDelta');if(mode==='batch')meta.textContent=d.totalDays+' CALENDAR DAYS';else meta.textContent=d.days?`DAY 1 → ${d.days} OF ${d.totalDays}`:'NO LEDGER DAYS YET';meta.classList.remove('down');out.innerHTML=d.rows.length?d.rows.map(p=>{const share=d.earned?Math.max(0,Math.min(100,p.earned/d.earned*100)):0;return `<article class="dashProduct"><div class="dashProductHead"><b>${esc(p.name)}</b><span class="dashBadge">${p.tx} TX</span></div><div class="dashRow"><span>EARNED</span><strong>${money(p.earned)}</strong></div><div class="dashRow"><span>SOLD</span><strong>${fmt(p.sold)}</strong></div><div class="dashRow"><span>NET</span><strong>${money(p.net)}</strong></div><div class="dashRow"><span>AVG / UNIT</span><strong>${money(p.sold?p.earned/p.sold:0)}</strong></div><div class="dashRow"><span>REMAINING</span><strong>${fmt(p.left)}</strong></div><div class="dashRow leftEarnRow"><span>LEFT TO EARN</span><strong>${money(p.leftToEarn)}</strong></div><div class="dashMeter"><i style="width:${share}%"></i></div></article>`}).join(''):'<div class="dashEmpty">NO SIGNAL // No transactions in this selected timeline window yet.</div>'}
function schedule(){if(queued)return;queued=true;setTimeout(()=>{queued=false;renderPicker();apply()},30)}
function boot(){loadSelected();let tries=0;const go=()=>{if(!installPicker()){if(tries++<60)setTimeout(go,100);return}$('#note')?.addEventListener('input',schedule,{passive:true});$('#note')?.addEventListener('change',schedule);window.addEventListener('goshaArchiveChanged',schedule);window.addEventListener('gosha-inventory-correction',schedule);$('#goshaDashboard')?.addEventListener('click',schedule);schedule()};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();