(()=>{
'use strict';
const $=s=>document.querySelector(s);
const fmt=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(Math.round((Number(n)+Number.EPSILON)*100)/100);
const money=n=>'€'+fmt(n);
const num=t=>{const n=parseFloat(String(t||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
let observer=null,queued=false,rendering=false;
function installStyle(){if($('#gosha-polish-style'))return;const s=document.createElement('style');s.id='gosha-polish-style';s.textContent=`
#goshaDashboard{border-color:rgba(134,255,40,.24)!important;background:linear-gradient(180deg,rgba(5,11,6,.985),rgba(0,0,0,.998))!important;box-shadow:0 24px 70px rgba(0,0,0,.5),inset 0 1px 0 rgba(214,255,198,.05),inset 0 0 70px rgba(76,255,60,.012)!important}
.dashHead{padding:16px 18px!important;background:linear-gradient(180deg,rgba(134,255,40,.025),transparent)!important}.dashHead .dashTitle{color:#dcebd8!important;text-shadow:0 0 18px rgba(134,255,40,.1)}
.dashControls{padding:12px!important;background:linear-gradient(180deg,rgba(4,8,4,.96),rgba(0,0,0,.96))!important}.dashArrow,.dashDaySelect,.dashScope{border-color:rgba(134,255,40,.18)!important;background:linear-gradient(180deg,rgba(134,255,40,.028),rgba(255,255,255,.006))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.018)!important}.dashArrow:hover,.dashDaySelect:hover,.dashScope:hover{border-color:rgba(134,255,40,.33)!important}
.dashStats{gap:8px!important;padding:10px!important;background:transparent!important}.dashStat{border:1px solid rgba(134,255,40,.105)!important;border-radius:14px!important;background:linear-gradient(180deg,rgba(255,255,255,.018),rgba(0,0,0,.94))!important;padding:15px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.018)!important}.dashStat small{color:rgba(143,164,138,.72)!important}.dashStat strong{font-size:20px!important;letter-spacing:-.02em}.dashStat.primary{border-color:rgba(134,255,40,.2)!important}.dashStat.primary strong,.dashStat.leftEarn strong{color:#cfffbd!important;text-shadow:0 0 18px rgba(134,255,40,.1)}
.dashProduct{border-color:rgba(134,255,40,.13)!important;background:linear-gradient(145deg,rgba(134,255,40,.018),rgba(255,255,255,.008) 45%,rgba(0,0,0,.2))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.018)!important}.dashProductHead b{font-size:12.5px!important}.dashRow{padding:6px 0!important;border-bottom:1px solid rgba(134,255,40,.035)}.dashRow:last-of-type{border-bottom:0}.dashRow.leftEarnRow strong{color:#cfffbd!important}
#allStrainsDash{border-color:rgba(134,255,40,.28)!important;border-radius:20px!important;background:radial-gradient(circle at 12% 0%,rgba(134,255,40,.055),transparent 34%),linear-gradient(180deg,rgba(4,9,4,.985),rgba(0,0,0,.995))!important;box-shadow:inset 0 1px 0 rgba(220,255,210,.05),0 18px 45px rgba(0,0,0,.26)!important}.allHead{padding:13px 14px!important;background:rgba(134,255,40,.015)}.allGrid{gap:8px!important;padding:10px!important;background:transparent!important}.allMetric{border:1px solid rgba(134,255,40,.1)!important;border-radius:12px!important;background:linear-gradient(180deg,rgba(255,255,255,.018),rgba(0,0,0,.95))!important;padding:13px!important}.allMetric.primary,.allMetric.leftEarn{border-color:rgba(134,255,40,.2)!important}.allMetric.primary strong,.allMetric.leftEarn strong{color:#cfffbd!important;text-shadow:0 0 16px rgba(134,255,40,.1)}.allMix{border-top:1px solid rgba(134,255,40,.08);padding-top:12px!important}
@media(max-width:620px){.dashStats{grid-template-columns:repeat(2,minmax(0,1fr))!important}.dashStat strong{font-size:18px!important}.allGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
`;document.head.appendChild(s)}
function rowValue(card,label){for(const r of card.querySelectorAll('.dashRow'))if(r.querySelector('span')?.textContent?.trim()===label)return num(r.querySelector('strong')?.textContent);return 0}
function ensureMain(){const stats=$('.dashStats');if(!stats)return null;let box=$('#dashLeftToEarn');if(!box){const wrap=document.createElement('div');wrap.className='dashStat leftEarn';wrap.innerHTML='<small>LEFT TO EARN</small><strong id="dashLeftToEarn">€0</strong>';stats.appendChild(wrap);box=$('#dashLeftToEarn')}return box}
function ensureAll(){const grid=$('#allStrainsDash .allGrid');if(!grid)return null;let box=$('#allLeftToEarn');if(!box){const wrap=document.createElement('div');wrap.className='allMetric leftEarn';wrap.innerHTML='<small>LEFT TO EARN</small><strong id="allLeftToEarn">€0</strong>';grid.appendChild(wrap);box=$('#allLeftToEarn')}return box}
function render(){installStyle();const cards=[...document.querySelectorAll('#dashProducts .dashProduct')];let total=0;for(const c of cards){const remaining=rowValue(c,'REMAINING');const avg=rowValue(c,'AVG / UNIT');const potential=Math.max(0,remaining*avg);total+=potential;let r=[...c.querySelectorAll('.dashRow')].find(x=>x.classList.contains('leftEarnRow'));if(!r){r=document.createElement('div');r.className='dashRow leftEarnRow';r.innerHTML='<span>LEFT TO EARN</span><strong>€0</strong>';const meter=c.querySelector('.dashMeter');c.insertBefore(r,meter||null)}const value=money(potential);if(r.querySelector('strong').textContent!==value)r.querySelector('strong').textContent=value}const main=ensureMain();if(main){const value=money(total);if(main.textContent!==value)main.textContent=value}const all=ensureAll();if(all){const value=money(total);if(all.textContent!==value)all.textContent=value}}
function observe(){const root=$('#dashProducts');if(observer&&root)observer.observe(root,{subtree:true,childList:true,characterData:true})}
function schedule(){if(rendering||queued)return;queued=true;requestAnimationFrame(()=>{queued=false;if(observer)observer.disconnect();rendering=true;try{render()}finally{rendering=false;observe()}})}
function boot(){let tries=0;const go=()=>{if(!$('#goshaDashboard')||!$('#dashProducts')){if(tries++<60)setTimeout(go,100);return}render();observer=new MutationObserver(schedule);observe()};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
