(()=>{
'use strict';
const $=s=>document.querySelector(s);
const fmt=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(Math.round((Number(n)+Number.EPSILON)*100)/100);
const money=n=>'€'+fmt(n);
const BASE={day:7,earned:2930,net:1000.2,leftToEarn:3500,sold:330,left:343,smoked:27,products:{'LEMON OG':{acquired:500,spent:3100,sold:235,left:250,smoked:15,total:2086.52},'BLUE DREAM':{acquired:200,spent:1400,sold:95,left:93,smoked:12,total:843.48}}};
let queued=false,observer=null,syncing=false;
function isCurrentNote(){const n=$('#note');if(!n)return false;const t=n.value.toUpperCase();return t.includes('LEMON OG 500/3100')&&t.includes('BLUE DREAM 200/1400')}
function pairs(s){return [...String(s||'').matchAll(/(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)/g)].map(m=>({qty:+m[1],price:+m[2]}))}
function live(){
 const n=$('#note');if(!n)return null;const lines=n.value.split(/\r?\n/),out={products:{},earned:0,sold:0,net:0,smokedDelta:0};let cur=null;
 for(const line of lines){const t=line.trim();if(!t)continue;const h=t.match(/^(.+?)\s+(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)\s*$/);if(h&&/[A-Za-zÀ-ž]/.test(h[1])){const name=h[1].trim().toUpperCase();cur=BASE.products[name]?{name,smoked:BASE.products[name].smoked,sold:0,earned:0}:null;if(cur)out.products[name]=cur;continue}if(!cur)continue;const sm=t.match(/^(?:smoked|used)\s*:?\s*(\d+(?:\.\d+)?)/i);if(sm){cur.smoked=+sm[1];continue}if(/^\s*(?:Total(?:\s+earned)?|Total\s+sold|Left)\s*:/i.test(t))continue;for(const x of pairs(line)){cur.sold+=x.qty;cur.earned+=x.price}}
 for(const [name,p] of Object.entries(out.products)){const b=BASE.products[name],cost=b.spent/b.acquired,sd=Math.max(0,p.smoked-b.smoked);out.sold+=p.sold;out.earned+=p.earned;out.net+=p.earned-p.sold*cost;out.smokedDelta+=sd;p.smokedDelta=sd;p.total=b.total+p.earned;p.totalSold=b.sold+p.sold;p.left=Math.max(0,b.left-p.sold-sd)}
 out.totalEarned=BASE.earned+out.earned;out.totalSold=BASE.sold+out.sold;out.totalNet=BASE.net+out.net;out.totalLeft=Math.max(0,BASE.left-out.sold-out.smokedDelta);out.leftToEarn=Math.max(0,BASE.leftToEarn-out.earned);return out
}
function set(sel,val){const e=$(sel);if(e&&e.textContent!==val)e.textContent=val}
function cleanAndSyncNotebook(){
 if(syncing||!isCurrentNote())return;const n=$('#note'),d=live();if(!n||!d)return;const lines=n.value.split(/\r?\n/),heads=[];for(let i=0;i<lines.length;i++){const h=lines[i].trim().match(/^(.+?)\s+(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)\s*$/);if(h&&BASE.products[h[1].trim().toUpperCase()])heads.push({i,name:h[1].trim().toUpperCase()})}if(!heads.length)return;const out=[...lines];for(let z=heads.length-1;z>=0;z--){const h=heads[z],end=z+1<heads.length?heads[z+1].i:out.length,p=d.products[h.name],b=BASE.products[h.name];if(!p)continue;const body=out.slice(h.i+1,end).filter(l=>!/^\s*(?:Total(?:\s+earned)?|Total\s+sold|Left|Smoked|Used)\s*:/i.test(l));while(body.length&&body[body.length-1].trim()==='')body.pop();out.splice(h.i,end-h.i,out[h.i],...body,'',`Total: €${fmt(p.total)}`,`Total sold: ${fmt(p.totalSold)}`,`Left: ${fmt(p.left)}`,`Smoked: ${fmt(p.smoked)}`,...(z<heads.length-1?['','']:[]))}const next=out.join('\n');if(next!==n.value){syncing=true;n.value=next;try{localStorage.setItem('goshaNoteV21',next);localStorage.setItem('goshaNote',next)}catch(_){}n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}));syncing=false}}
function render(){
 if(!isCurrentNote())return;const d=live();if(!d)return;const batchActive=$('#goshaDashboard .dashScope[data-mode="batch"]')?.classList.contains('active'),dayActive=$('#dashDaySelect')?.classList.contains('active'),dayText=$('#dashDaySelect')?.textContent||'';
 if(batchActive){set('#dashEarned',money(d.totalEarned));set('#dashSold',fmt(d.totalSold));set('#dashProfit',money(d.totalNet));set('#dashAverage',money(d.totalSold?d.totalEarned/d.totalSold:0));set('#dashLeft',fmt(d.totalLeft));set('#dashLeftToEarn',money(d.leftToEarn));set('#dashScopeLabel','WHOLE BATCH');set('#dashDelta','DAY 7 // LIVE TOTAL')}
 if(dayActive&&/DAY\s+7\b/i.test(dayText)){set('#dashEarned',money(d.earned));set('#dashSold',fmt(d.sold));set('#dashProfit',money(d.net));set('#dashAverage',money(d.sold?d.earned/d.sold:0));set('#dashLeft',fmt(d.totalLeft));set('#dashScopeLabel','DAY 7 SIGNAL');set('#dashDelta','TODAY')}
 set('#allEarned',money(d.totalEarned));set('#allSold',fmt(d.totalSold));set('#allNet',money(d.totalNet));set('#allAvg',money(d.totalSold?d.totalEarned/d.totalSold:0));set('#allRemaining',fmt(d.totalLeft));set('#allLeftToEarn',money(d.leftToEarn));set('#allStrainCount','2 STRAINS');const day=$('#dashDaySelect');if(day&&!day.classList.contains('active'))day.textContent='DAY 7 / 50'
}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}
function boot(){let tries=0;const go=()=>{if(!$('#goshaDashboard')||!$('#note')){if(tries++<60)setTimeout(go,100);return}render();observer=new MutationObserver(schedule);observer.observe($('#goshaDashboard'),{subtree:true,childList:true,characterData:true});$('#note').addEventListener('input',schedule,{passive:true});$('#note').addEventListener('change',schedule);document.addEventListener('click',e=>{if(e.target?.id==='calcBtn'&&isCurrentNote()){e.preventDefault();e.stopImmediatePropagation();cleanAndSyncNotebook();render()}},true)};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();