(()=>{
'use strict';
const QUICK_MS=5*60*1000;
const FORCE_MIN_MS=60*1000;
const PRUNE_MS=30*60*1000;
const LAST_QUICK='goshaSecureSavesLastQuickV1';
const LAST_CHECKSUM='goshaSecureSavesLastChecksumV1';
let timer=0,lastPrune=0;
const $=s=>document.querySelector(s);
function bridge(){try{return window.AndroidSecureSaves||null}catch(_){return null}}
function hash(text){let h=2166136261;text=String(text??'');for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function noteText(){return $('#note')?.value??''}
function dayKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),x=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${x}`}
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function nativeReady(){const b=bridge();try{return !!b&&typeof b.saveSnapshot==='function'&&b.isAvailable()}catch(_){return false}}
function saveDaily(text){const b=bridge();if(!nativeReady())return false;try{return !!b.saveSnapshot(`daily-${dayKey()}.gsv`,text)}catch(_){return false}}
function saveQuick(text,force=false){const b=bridge();if(!nativeReady())return false;const now=Date.now(),sum=hash(text);let last=0,prev='';try{last=+localStorage.getItem(LAST_QUICK)||0;prev=localStorage.getItem(LAST_CHECKSUM)||''}catch(_){}
 if(!force&&now-last<QUICK_MS)return false;if(prev===sum)return false;
 try{const ok=!!b.saveSnapshot(`quick-${now}.gsv`,text);if(ok){localStorage.setItem(LAST_QUICK,String(now));localStorage.setItem(LAST_CHECKSUM,sum)}return ok}catch(_){return false}}
function prune(){const b=bridge();if(!nativeReady())return;const now=Date.now();if(now-lastPrune<PRUNE_MS)return;lastPrune=now;try{b.pruneSnapshots(now)}catch(_){}}
function checkpoint(force=false){if(!nativeReady())return;const text=noteText();saveDaily(text);saveQuick(text,force);prune()}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>checkpoint(false),1800)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function labelFor(name){if(name.startsWith('daily-'))return `DAILY · ${name.slice(6,16)}`;const m=name.match(/^quick-(\d+)\.gsv$/);if(!m)return name;const d=new Date(+m[1]);return `QUICK · ${d.toLocaleString()}`}
function listNames(){const b=bridge();if(!nativeReady())return[];try{const a=JSON.parse(b.listSnapshots()||'[]');return Array.isArray(a)?a.filter(x=>typeof x==='string'):[]}catch(_){return[]}}
function ensureStyles(){if($('#secureSavesStyle'))return;const s=document.createElement('style');s.id='secureSavesStyle';s.textContent=`
.secureSavesCard{grid-column:1/-1}.secureSavesTop{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.secureSavesMeta{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:7px;margin:10px 0}.secureSavesMeta div{border:1px solid rgba(134,255,40,.09);border-radius:10px;padding:8px 9px;color:#71806d;font:650 10px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace}.secureSavesMeta b{display:block;color:#d9e7d5;margin-top:2px}.secureSavesList{max-height:330px;overflow:auto;border-top:1px solid rgba(134,255,40,.08);margin-top:10px;padding-top:7px}.secureSaveRow{display:flex;align-items:center;gap:8px;padding:8px 3px;border-bottom:1px solid rgba(134,255,40,.06)}.secureSaveRow span{min-width:0;flex:1;color:#a8b6a4;font:600 10px/1.25 ui-monospace,SFMono-Regular,Menlo,monospace}.secureSaveRow button{padding:6px 9px;font-size:10px}.secureSavesHint{color:#667462!important;font-size:11px!important}.secureSavesDanger{border-color:rgba(255,194,86,.2)!important;color:#ffe2a8!important}
`;document.head.appendChild(s)}
function ensureCard(){const grid=$('#settingsView .settingsGrid');if(!grid)return null;let c=$('#secureSavesCard');if(c)return c;c=document.createElement('div');c.id='secureSavesCard';c.className='setting secureSavesCard';c.innerHTML=`<h3>Encrypted saves</h3><p>Current notebook stays instant. Separate encrypted checkpoints keep quick history for 48 hours and one rolling daily checkpoint for 2 years.</p><div class="secureSavesMeta"><div>ENCRYPTION<b id="secureCrypto">—</b></div><div>BACKUP FOLDER<b id="secureFolder">—</b></div><div>SAVES<b id="secureCount">—</b></div></div><div class="secureSavesTop"><button class="btn" id="secureFolderBtn" type="button">Choose backup folder</button><button class="btn" id="secureRefreshBtn" type="button">Refresh saves</button><button class="btn secureSavesDanger" id="secureRecoveryBtn" type="button">Copy recovery key</button><button class="btn" id="secureImportBtn" type="button">Import recovery key</button></div><p class="secureSavesHint">Pick a cloud-backed folder (for example a folder exposed by your Android file picker) to mirror encrypted .gsv files off-device. Keep the recovery key somewhere separate; without it, a new phone cannot decrypt those files.</p><div class="secureSavesList" id="secureSavesList"></div>`;grid.appendChild(c);
 $('#secureFolderBtn').onclick=chooseFolder;$('#secureRefreshBtn').onclick=render;$('#secureRecoveryBtn').onclick=copyRecoveryKey;$('#secureImportBtn').onclick=importRecoveryKey;return c}
function chooseFolder(){const b=bridge();if(!nativeReady())return toast('Install native v3 first');try{b.chooseBackupFolder()}catch(_){toast('Could not open folder picker')}}
async function copyRecoveryKey(){const b=bridge();if(!nativeReady())return toast('Install native v3 first');try{const key=b.getRecoveryKey();if(!key)return toast('Recovery key unavailable');await navigator.clipboard.writeText(key);toast('Recovery key copied')}catch(_){toast('Could not copy recovery key')}}
function importRecoveryKey(){const b=bridge();if(!nativeReady())return toast('Install native v3 first');const key=prompt('Paste the GO$HA recovery key. This changes which encrypted saves this device can open.');if(!key)return;if(!confirm('Replace this device’s encrypted-save key with the pasted recovery key? Existing local encrypted saves made with another key may become unreadable.'))return;try{if(b.importRecoveryKey(key.trim())){toast('Recovery key imported');checkpoint(true);render()}else toast('Invalid recovery key')}catch(_){toast('Recovery key import failed')}}
function restore(name){const b=bridge();if(!nativeReady())return;let text;try{text=b.loadSnapshot(name)}catch(_){return toast('Could not decrypt save')}if(typeof text!=='string'||text.length===0)return toast('Save is unreadable or empty');if(!confirm(`Restore ${labelFor(name)}? Your current notebook is saved before the restore.`))return;const n=$('#note');if(!n)return;try{window.GoshaImmediateSaveText?.(n.value)}catch(_){}n.value=text;n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}));try{window.GoshaImmediateSaveText?.(text)}catch(_){}toast('Save restored');setTimeout(()=>checkpoint(true),50)}
function render(){ensureStyles();const c=ensureCard();if(!c)return;const ready=nativeReady();if(!ready){$('#secureCrypto').textContent='Native v3 required';$('#secureFolder').textContent='Unavailable';$('#secureCount').textContent='—';$('#secureSavesList').innerHTML='<div class="secureSaveRow"><span>Install the latest Android update to enable Keystore-encrypted saves.</span></div>';return}const b=bridge();try{$('#secureCrypto').textContent=b.deviceSecurity()||'AES-256-GCM'}catch(_){$('#secureCrypto').textContent='AES-256-GCM'}try{$('#secureFolder').textContent=b.hasBackupFolder()?(b.getBackupFolderLabel()||'Selected'):'Not selected'}catch(_){$('#secureFolder').textContent='Not selected'}const names=listNames();const daily=names.filter(n=>n.startsWith('daily-')).length,quick=names.length-daily;$('#secureCount').textContent=`${daily} daily · ${quick} quick`;const box=$('#secureSavesList');if(!names.length){box.innerHTML='<div class="secureSaveRow"><span>No encrypted checkpoints yet.</span></div>';return}box.innerHTML=names.slice(0,120).map(n=>`<div class="secureSaveRow"><span>${esc(labelFor(n))}</span><button class="btn" data-restore="${esc(n)}" type="button">RESTORE</button></div>`).join('');box.querySelectorAll('[data-restore]').forEach(btn=>btn.onclick=()=>restore(btn.dataset.restore))}
window.goshaSecureSavesFolderChanged=ok=>{toast(ok?'Encrypted backup folder connected':'Folder access failed');render()};
function boot(){ensureStyles();let tries=0;const go=()=>{const n=$('#note');if(!n||!$('#settingsView')){if(tries++<80)setTimeout(go,100);return}render();if(nativeReady()){checkpoint(false);n.addEventListener('input',schedule,{passive:true});n.addEventListener('change',()=>checkpoint(false));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){const now=Date.now();let last=0;try{last=+localStorage.getItem(LAST_QUICK)||0}catch(_){}checkpoint(now-last>=FORCE_MIN_MS)}else render()});window.addEventListener('pagehide',()=>checkpoint(true));setInterval(()=>checkpoint(false),QUICK_MS)}};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();