(()=>{
'use strict';
const NOTE_KEY='goshaNoteV21',LEGACY_KEY='goshaNote',BACKUP_KEY='goshaPreDemoBackupV36',DEMO_FLAG='goshaDemoActiveV36';
const note=()=>document.querySelector('#note');
const style=document.createElement('style');style.textContent=`:root{--v36-line:rgba(114,255,116,.13);--v36-text:#e8eee8}.panel{background:linear-gradient(180deg,rgba(6,10,6,.98),rgba(1,3,1,.99))!important;border-color:var(--v36-line)!important;border-radius:24px!important;box-shadow:0 14px 42px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.015)!important;overflow:hidden}.panelHead{padding-top:18px!important;padding-bottom:16px!important;border-bottom:1px solid rgba(114,255,116,.095)!important;background:linear-gradient(180deg,rgba(255,255,255,.014),transparent)!important}#note{background:#000!important;color:var(--v36-text)!important;border:0!important;box-shadow:none!important;line-height:1.62!important;padding:28px 28px 34px!important;caret-color:#8cff72!important;letter-spacing:.005em!important}#note::placeholder{color:rgba(220,235,220,.25)!important}#saveStatus{background:transparent!important;border-color:rgba(114,255,116,.17)!important;color:rgba(190,255,190,.56)!important;box-shadow:none!important;font-size:.82em!important;letter-spacing:.045em!important}.btn,.navBtn,.bottomNav button{background:rgba(255,255,255,.018)!important;border-color:rgba(114,255,116,.17)!important;color:rgba(228,240,228,.78)!important;box-shadow:none!important}.btn.primary,#calcBtn{background:rgba(114,255,116,.065)!important;border-color:rgba(114,255,116,.28)!important;color:#dfffe0!important}.bottomNav{background:rgba(2,4,2,.96)!important;border-color:rgba(114,255,116,.12)!important;backdrop-filter:blur(16px)!important;-webkit-backdrop-filter:blur(16px)!important;box-shadow:0 -12px 35px rgba(0,0,0,.32)!important}.setting,.stat,.card{border-color:rgba(114,255,116,.11)!important;background:rgba(255,255,255,.012)!important;box-shadow:none!important}#restorePreDemo{margin-top:10px!important}`;document.head.appendChild(style);
function saveNow(){const n=note();if(!n)return;try{localStorage.setItem(NOTE_KEY,n.value);localStorage.setItem(LEGACY_KEY,n.value)}catch(_){}}
function removeInstruction(){for(const el of document.querySelectorAll('p,div,small,footer,span')){const t=(el.textContent||'').trim();if(t.startsWith('Product headings such as')||t.includes('define starting stock and cost. Heading values are excluded'))el.remove()}}
function suppressSavedPopup(){const toast=document.querySelector('#toast');if(!toast)return;const clean=()=>{const t=(toast.textContent||'').trim().toLowerCase();if(t==='saved locally'||t==='saved local'||t==='saved'||(t.includes('saved')&&t.includes('local'))){toast.classList.remove('show');toast.style.opacity='0';setTimeout(()=>toast.style.opacity='',180)}};new MutationObserver(clean).observe(toast,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class']});clean()}
function addResultGap(){const n=note();if(!n)return;let lines=n.value.split(/\r?\n/);for(let i=0;i<lines.length;i++){if(/^\s*Total:\s*/i.test(lines[i])){let j=i-1;while(j>=0&&lines[j].trim()==='')j--;const blanks=i-j-1;if(blanks!==1){lines.splice(j+1,blanks,'');i=j+2}}}const next=lines.join('\n');if(next!==n.value){const pos=n.selectionStart;n.value=next;saveNow();try{n.setSelectionRange(Math.min(pos,next.length),Math.min(pos,next.length))}catch(_){}}}
function wireAutosave(){const n=note();if(!n||n.dataset.v36Autosave)return;n.dataset.v36Autosave='1';let timer;const immediate=()=>{clearTimeout(timer);saveNow()};n.addEventListener('input',()=>{saveNow();clearTimeout(timer);timer=setTimeout(saveNow,120)},{passive:true});n.addEventListener('change',immediate);n.addEventListener('blur',immediate);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')immediate()});window.addEventListener('pagehide',immediate);window.addEventListener('beforeunload',immediate)}
function installDemoControls(){const n=note();if(!n)return;const demo=document.querySelector('#demoBtnV24,#demoBtn');if(demo&&!demo.dataset.v36Backup){demo.dataset.v36Backup='1';demo.addEventListener('click',()=>{try{if(localStorage.getItem(DEMO_FLAG)!=='1'){localStorage.setItem(BACKUP_KEY,n.value);localStorage.setItem(DEMO_FLAG,'1')}}catch(_){}},{capture:true})}const grid=document.querySelector('#settingsView .settingsGrid');if(!grid)return;let card=document.querySelector('#restorePreDemoCard');if(!card){card=document.createElement('div');card.className='setting';card.id='restorePreDemoCard';card.innerHTML='<h3>Previous notebook</h3><p>Demo mode keeps a protected copy of your notebook.</p><button class="btn" id="restorePreDemo">Return to previous</button>';grid.appendChild(card);card.querySelector('#restorePreDemo').addEventListener('click',()=>{let prev=null;try{prev=localStorage.getItem(BACKUP_KEY)}catch(_){}if(prev===null)return;n.value=prev;saveNow();try{localStorage.removeItem(DEMO_FLAG);localStorage.removeItem(BACKUP_KEY)}catch(_){}n.dispatchEvent(new Event('input',{bubbles:true}));refresh();const toast=document.querySelector('#toast');if(toast){toast.textContent='Previous notebook restored';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1000)}})}function refresh(){let has=false;try{has=localStorage.getItem(BACKUP_KEY)!==null}catch(_){}card.style.display=has?'':'none'}refresh()}
function boot(){removeInstruction();suppressSavedPopup();wireAutosave();installDemoControls();const calc=document.querySelector('#calcBtn');if(calc&&!calc.dataset.v36Gap){calc.dataset.v36Gap='1';calc.addEventListener('click',()=>setTimeout(()=>{addResultGap();saveNow()},0))}setTimeout(()=>{removeInstruction();installDemoControls();wireAutosave()},150);setTimeout(removeInstruction,800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();