(()=>{
'use strict';
const NOTE_KEY='goshaNoteV21',LEGACY_NOTE_KEY='goshaNote',VAULT_KEY='goshaVaultLocalV1',UNDO_KEY='goshaRecoveryUndo';
const DB_NAME='GoshaNotebookVault',DB_STORE='vault',DB_RECORD='notebook';
const CACHE_NAME='gosha-notebook-vault-v1',CACHE_URL=new URL('./__gosha_notebook_backup__',location.href).href;
let suppress=false,timer=null,lastPayload=null;
const $=s=>document.querySelector(s);
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function checksum(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
function makePayload(text,updatedAt=Date.now()){return {version:1,text:String(text??''),updatedAt,checksum:checksum(String(text??''))}}
function valid(p){return p&&typeof p.text==='string'&&Number.isFinite(+p.updatedAt)&&(p.checksum===undefined||p.checksum===checksum(p.text))}
function parse(raw){if(!raw)return null;try{const p=JSON.parse(raw);return valid(p)?p:null}catch(_){return null}}
function isLemonBlue(text){const t=String(text||'').toUpperCase();return t.includes('LEMON OG 500/3100')&&t.includes('BLUE DREAM 200/1400')}
function ledgerTxCount(text){
 const lines=String(text||'').split(/\r?\n/);let known=false,count=0;
 for(const line of lines){const t=line.trim();if(!t)continue;const h=t.match(/^(.+?)\s+(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)\s*$/);if(h){const name=h[1].trim().toUpperCase();known=name==='LEMON OG'||name==='BLUE DREAM';continue}if(!known||/^\s*(?:Total(?:\s+earned)?|Total\s+sold|Left|Smoked|Used)\s*:/i.test(t))continue;count+=(line.match(/(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)/g)||[]).length}return count
}
function ledgerMeaningfulLines(text){return String(text||'').split(/\r?\n/).filter(x=>{const t=x.trim();return t&&!/^\s*(?:Total(?:\s+earned)?|Total\s+sold|Left|Smoked|Used)\s*:/i.test(t)}).length}
function candidateScore(p){const text=p?.text||'';return {same:isLemonBlue(text)?1:0,tx:ledgerTxCount(text),lines:ledgerMeaningfulLines(text),len:text.length,updated:+p?.updatedAt||0}}
function richer(a,b){const A=candidateScore(a),B=candidateScore(b);for(const k of ['same','tx','lines','len','updated']){if(A[k]!==B[k])return A[k]>B[k]}return false}
function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}
async function idbRead(){try{const db=await openDb();return await new Promise(resolve=>{const tx=db.transaction(DB_STORE,'readonly'),r=tx.objectStore(DB_STORE).get(DB_RECORD);r.onsuccess=()=>resolve(valid(r.result)?r.result:null);r.onerror=()=>resolve(null);tx.oncomplete=()=>db.close()})}catch(_){return null}}
async function idbWrite(p){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(p,DB_RECORD);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return true}catch(_){return false}}
async function cacheRead(){try{if(!('caches'in window))return null;const c=await caches.open(CACHE_NAME),r=await c.match(CACHE_URL);return r?parse(await r.text()):null}catch(_){return null}}
async function cacheWrite(p){try{if(!('caches'in window))return false;const c=await caches.open(CACHE_NAME);await c.put(CACHE_URL,new Response(JSON.stringify(p),{headers:{'content-type':'application/json'}}));return true}catch(_){return false}}
function nativeRead(){try{if(window.AndroidVault&&typeof AndroidVault.load==='function')return parse(AndroidVault.load())}catch(_){}return null}
function nativeWrite(p){try{if(window.AndroidVault&&typeof AndroidVault.save==='function'){AndroidVault.save(JSON.stringify(p));return true}}catch(_){}return false}
function localRead(){try{return parse(localStorage.getItem(VAULT_KEY))}catch(_){return null}}
function legacyCandidates(){const out=[];const add=(source,text,updatedAt=0)=>{if(typeof text!=='string'||!text.trim()||out.some(x=>x.text===text))return;let payload=parse(text);if(payload){payload={...payload,source};out.push(payload);return}const p=makePayload(text,updatedAt);p.source=source;out.push(p)};try{add(NOTE_KEY,localStorage.getItem(NOTE_KEY));add(LEGACY_NOTE_KEY,localStorage.getItem(LEGACY_NOTE_KEY));for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(/gosha.*(backup|recover|note)|note.*gosha|goshaBeforeDay7Reconstruction/i.test(k))add(k,localStorage.getItem(k))}}catch(_){}return out}
async function readAll(){const [idb,cache]=await Promise.all([idbRead(),cacheRead()]);const local=localRead(),native=nativeRead();return [{name:'LOCAL',payload:local},{name:'INDEX',payload:idb},{name:'CACHE',payload:cache},{name:'NATIVE',payload:native}].filter(x=>valid(x.payload))}
async function writeAll(text){const p=makePayload(text);lastPayload=p;let local=false;try{localStorage.setItem(VAULT_KEY,JSON.stringify(p));localStorage.setItem(NOTE_KEY,p.text);localStorage.setItem(LEGACY_NOTE_KEY,p.text);local=true}catch(_){}const [idb,cache]=await Promise.all([idbWrite(p),cacheWrite(p)]);const native=nativeWrite(p);updateHealth({local,idb,cache,native});return p}
function scheduleSave(){if(suppress)return;clearTimeout(timer);timer=setTimeout(()=>{const n=$('#note');if(n)writeAll(n.value)},120)}
function updateHealth(s){const map={local:'#vaultLocal',idb:'#vaultIndex',cache:'#vaultCache',native:'#vaultNative'};for(const [k,sel] of Object.entries(map)){const e=$(sel);if(!e)continue;const ok=!!s[k];e.textContent=ok?'SYNC':'OFFLINE';e.classList.toggle('ok',ok)}const total=Object.values(s).filter(Boolean).length;const e=$('#vaultCount');if(e)e.textContent=total+'/4';const ring=$('#deckRing');if(ring)ring.dataset.health=String(total);const state=$('#deckState');if(state)state.textContent=total>=3?'VAULT STABLE':total>=2?'VAULT DEGRADED':'VAULT ALERT'}
async function recoverCandidate(){const n=$('#note');if(!n)return;const current=makePayload(n.value,Date.now());const all=await readAll();const candidates=[current];for(const x of all)candidates.push({...x.payload,source:x.name});for(const p of legacyCandidates())candidates.push(p);let best=current;for(const p of candidates)if(richer(p,best))best=p;if(best.text===n.value){toast('Current notebook is richest saved copy');return}try{localStorage.setItem(UNDO_KEY,n.value)}catch(_){}suppress=true;n.value=best.text;suppress=false;await writeAll(best.text);n.dispatchEvent(new Event('input',{bubbles:true}));toast('Recovered richer save: '+(best.source||'vault'))}
function installSettings(){const grid=$('#settingsView .settingsGrid');if(!grid||$('#goshaVaultCard'))return false;const c=document.createElement('div');c.className='setting vaultSetting';c.id='goshaVaultCard';c.innerHTML='<h3>DATA VAULT</h3><p>Redundant notebook persistence and recovery.</p><div class="vaultMini"><span>LOCAL <b id="vaultLocal">—</b></span><span>INDEX <b id="vaultIndex">—</b></span><span>CACHE <b id="vaultCache">—</b></span><span>NATIVE <b id="vaultNative">—</b></span></div><button class="btn" id="goshaRecoverSettings" type="button">Recover richest saved copy</button><button class="btn" id="goshaUndoSettings" type="button" style="margin-top:10px">Undo recovery</button>';grid.appendChild(c);$('#goshaRecoverSettings').onclick=recoverCandidate;$('#goshaUndoSettings').onclick=async()=>{let old=null;try{old=localStorage.getItem(UNDO_KEY)}catch(_){}if(old===null){toast('No recovery undo available');return}const n=$('#note');if(!n)return;const now=n.value;suppress=true;n.value=old;suppress=false;try{localStorage.setItem(UNDO_KEY,now)}catch(_){}await writeAll(old);n.dispatchEvent(new Event('input',{bubbles:true}));toast('Recovery undone')};return true}
function installDeckStyles(){if($('#goshaDeckStyle'))return;const s=document.createElement('style');s.id='goshaDeckStyle';s.textContent=`.app{padding-bottom:116px!important}.bottomNav.vaultDeck{height:82px!important;bottom:max(10px,env(safe-area-inset-bottom))!important;left:10px!important;right:10px!important;display:grid!important;grid-template-columns:minmax(126px,1.45fr) minmax(82px,1fr) minmax(82px,1fr)!important;align-items:stretch!important;border:1px solid rgba(114,255,116,.22)!important;border-radius:19px!important;background:linear-gradient(180deg,rgba(3,9,5,.97),rgba(0,2,1,.985))!important;overflow:hidden!important}.vaultDeckStatus{display:grid!important;grid-template-columns:26px 1fr;grid-template-rows:1fr 1fr;align-items:center;column-gap:9px;padding:11px 12px!important;border-right:1px solid rgba(114,255,116,.13);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.deckRing{grid-row:1/3;width:24px;height:24px;border-radius:50%;border:1px solid rgba(134,255,40,.32)}.deckState{align-self:end;color:rgba(222,255,216,.82);font-size:.68rem;letter-spacing:.12em}.vaultDeckStatus b{align-self:start;color:#86ff28;font-size:.8rem}.vaultMini{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:12px 0 15px}.vaultMini span{border:1px solid rgba(114,255,116,.11);border-radius:9px;padding:8px 9px;font:600 .67rem/1.1 ui-monospace,SFMono-Regular,Menlo,monospace;color:rgba(211,226,208,.58)}.vaultMini b{float:right}.vaultMini b.ok{color:#86ff28}#goshaRecoverHeader{display:none!important}`;document.head.appendChild(s)}
function installDashboard(){const nav=$('.bottomNav');if(!nav)return false;installDeckStyles();nav.classList.add('vaultDeck');const old=$('#vaultDeckStatus');if(old)old.remove();const s=document.createElement('div');s.id='vaultDeckStatus';s.className='vaultDeckStatus';s.innerHTML='<span class="deckRing" id="deckRing" data-health="0"></span><span class="deckState" id="deckState">VAULT INIT</span><b id="vaultCount">—/4</b>';nav.prepend(s);return true}
async function boot(){const n=$('#note');if(!n)return;const huge=$('#goshaRecoverHeader');if(huge)huge.remove();installSettings();installDashboard();n.addEventListener('input',scheduleSave,{passive:true});n.addEventListener('change',scheduleSave);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')writeAll(n.value)});window.addEventListener('pagehide',()=>writeAll(n.value));
 const current=makePayload(n.value,Date.now()),all=await readAll(),candidates=[current];for(const x of all)candidates.push({...x.payload,source:x.name});for(const p of legacyCandidates())candidates.push(p);let best=current;for(const p of candidates)if(richer(p,best))best=p;
 if(best.text!==n.value){try{localStorage.setItem(UNDO_KEY,n.value)}catch(_){}suppress=true;n.value=best.text;suppress=false;n.dispatchEvent(new Event('input',{bubbles:true}));toast('Richer notebook restored')}
 await writeAll(n.value);const state={local:true,idb:!!(await idbRead()),cache:!!(await cacheRead()),native:!!nativeRead()};updateHealth(state)}
function start(){let tries=0;const go=()=>{if($('#note'))boot();else if(tries++<30)setTimeout(go,100)};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();