(()=>{
'use strict';
const NOTE_KEY='goshaNoteV21',LEGACY_NOTE_KEY='goshaNote',VAULT_KEY='goshaVaultLocalV1',UNDO_KEY='goshaRecoveryUndo';
const DB_NAME='GoshaNotebookVault',DB_STORE='vault',DB_RECORD='notebook';
const CACHE_NAME='gosha-notebook-vault-v1',CACHE_URL=new URL('./__gosha_notebook_backup__',location.href).href;
let suppress=false,timer=null,lastPayload=null;
const $=s=>document.querySelector(s);
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function checksum(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
function makePayload(text,updatedAt=Date.now()){return {version:1,text:String(text??''),updatedAt,checksum:checksum(String(text??''))}}
function valid(p){return p&&typeof p.text==='string'&&Number.isFinite(+p.updatedAt)&&(p.checksum===undefined||p.checksum===checksum(p.text))}
function parse(raw){if(!raw)return null;try{const p=JSON.parse(raw);return valid(p)?p:null}catch(_){return null}}
function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}
async function idbRead(){try{const db=await openDb();return await new Promise(resolve=>{const tx=db.transaction(DB_STORE,'readonly'),r=tx.objectStore(DB_STORE).get(DB_RECORD);r.onsuccess=()=>resolve(valid(r.result)?r.result:null);r.onerror=()=>resolve(null);tx.oncomplete=()=>db.close()})}catch(_){return null}}
async function idbWrite(p){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(p,DB_RECORD);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return true}catch(_){return false}}
async function cacheRead(){try{if(!('caches'in window))return null;const c=await caches.open(CACHE_NAME),r=await c.match(CACHE_URL);return r?parse(await r.text()):null}catch(_){return null}}
async function cacheWrite(p){try{if(!('caches'in window))return false;const c=await caches.open(CACHE_NAME);await c.put(CACHE_URL,new Response(JSON.stringify(p),{headers:{'content-type':'application/json'}}));return true}catch(_){return false}}
function nativeRead(){try{if(window.AndroidVault&&typeof AndroidVault.load==='function')return parse(AndroidVault.load())}catch(_){}return null}
function nativeWrite(p){try{if(window.AndroidVault&&typeof AndroidVault.save==='function'){AndroidVault.save(JSON.stringify(p));return true}}catch(_){}return false}
function localRead(){try{return parse(localStorage.getItem(VAULT_KEY))}catch(_){return null}}
function legacyCandidates(){const out=[];const add=(source,text,updatedAt=0)=>{if(typeof text!=='string'||!text.trim()||out.some(x=>x.text===text))return;out.push(makePayload(text,updatedAt));out[out.length-1].source=source};try{add(NOTE_KEY,localStorage.getItem(NOTE_KEY));add(LEGACY_NOTE_KEY,localStorage.getItem(LEGACY_NOTE_KEY));for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(/gosha.*(backup|recover|note)|note.*gosha/i.test(k))add(k,localStorage.getItem(k))}}catch(_){}return out}
async function readAll(){const [idb,cache]=await Promise.all([idbRead(),cacheRead()]);const local=localRead(),native=nativeRead();return [{name:'LOCAL',payload:local},{name:'INDEX',payload:idb},{name:'CACHE',payload:cache},{name:'NATIVE',payload:native}].filter(x=>valid(x.payload))}
async function writeAll(text){const p=makePayload(text);lastPayload=p;let local=false;try{localStorage.setItem(VAULT_KEY,JSON.stringify(p));localStorage.setItem(NOTE_KEY,p.text);localStorage.setItem(LEGACY_NOTE_KEY,p.text);local=true}catch(_){}const [idb,cache]=await Promise.all([idbWrite(p),cacheWrite(p)]);const native=nativeWrite(p);updateHealth({local,idb,cache,native});return p}
function scheduleSave(){if(suppress)return;clearTimeout(timer);timer=setTimeout(()=>{const n=$('#note');if(n)writeAll(n.value)},120)}
function updateHealth(s){const map={local:'#vaultLocal',idb:'#vaultIndex',cache:'#vaultCache',native:'#vaultNative'};for(const [k,sel] of Object.entries(map)){const e=$(sel);if(!e)continue;const ok=!!s[k];e.textContent=ok?'SYNC':'OFFLINE';e.classList.toggle('ok',ok)}const total=Object.values(s).filter(Boolean).length;const e=$('#vaultCount');if(e)e.textContent=total+'/4 LAYERS'}
async function recoverCandidate(){const n=$('#note');if(!n)return;const current=n.value;const all=await readAll();const candidates=[];for(const x of all)if(x.payload.text!==current)candidates.push({...x.payload,source:x.name});for(const p of legacyCandidates())if(p.text!==current&&!candidates.some(x=>x.text===p.text))candidates.push(p);if(!candidates.length){toast('No older recoverable copy found');return}candidates.sort((a,b)=>(+b.updatedAt||0)-(+a.updatedAt||0));const preferred=candidates.find(x=>/backup|recover/i.test(x.source||''))||candidates[0];try{localStorage.setItem(UNDO_KEY,current)}catch(_){}suppress=true;n.value=preferred.text;suppress=false;await writeAll(preferred.text);n.dispatchEvent(new Event('input',{bubbles:true}));toast('Recovered from '+(preferred.source||'vault'))}
function installSettings(){const grid=$('#settingsView .settingsGrid');if(!grid||$('#goshaVaultCard'))return false;const c=document.createElement('div');c.className='setting vaultSetting';c.id='goshaVaultCard';c.innerHTML='<h3>DATA VAULT</h3><p>Redundant notebook persistence and recovery.</p><div class="vaultMini"><span>LOCAL <b id="vaultLocal">—</b></span><span>INDEX <b id="vaultIndex">—</b></span><span>CACHE <b id="vaultCache">—</b></span><span>NATIVE <b id="vaultNative">—</b></span></div><button class="btn" id="goshaRecoverSettings" type="button">Recover saved copy</button><button class="btn" id="goshaUndoSettings" type="button" style="margin-top:10px">Undo recovery</button>';grid.appendChild(c);$('#goshaRecoverSettings').onclick=recoverCandidate;$('#goshaUndoSettings').onclick=async()=>{let old=null;try{old=localStorage.getItem(UNDO_KEY)}catch(_){}if(old===null){toast('No recovery undo available');return}const n=$('#note');if(!n)return;const now=n.value;suppress=true;n.value=old;suppress=false;try{localStorage.setItem(UNDO_KEY,now)}catch(_){}await writeAll(old);n.dispatchEvent(new Event('input',{bubbles:true}));toast('Recovery undone')};return true}
function installDashboard(){const nav=$('.bottomNav');if(!nav)return false;nav.classList.add('vaultDeck');if(!$('#vaultDeckStatus')){const s=document.createElement('div');s.id='vaultDeckStatus';s.className='vaultDeckStatus';s.innerHTML='<span class="deckPulse"></span><span>VAULT</span><b id="vaultCount">—/4 LAYERS</b>';nav.prepend(s)}return true}
async function boot(){const n=$('#note');if(!n)return;installSettings();installDashboard();n.addEventListener('input',scheduleSave,{passive:true});n.addEventListener('change',scheduleSave);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')writeAll(n.value)});window.addEventListener('pagehide',()=>writeAll(n.value));const all=await readAll();const best=all.sort((a,b)=>b.payload.updatedAt-a.payload.updatedAt)[0];if(best&&best.payload.text!==n.value){suppress=true;n.value=best.payload.text;suppress=false;n.dispatchEvent(new Event('input',{bubbles:true}));toast('Vault copy restored')}await writeAll(n.value);const state={local:true,idb:!!(await idbRead()),cache:!!(await cacheRead()),native:!!nativeRead()};updateHealth(state)}
function start(){let tries=0;const go=()=>{if($('#note'))boot();else if(tries++<30)setTimeout(go,100)};go()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();